FROM node:18-alpine

WORKDIR /app

# Install laravel-echo-server globally
RUN npm set progress=false \
 && npm i -g laravel-echo-server --silent

COPY laravel-echo-server.json /app/laravel-echo-server.json

EXPOSE 6001

CMD ["laravel-echo-server", "start", "--config", "/app/laravel-echo-server.json"]
