version: '3.7'
services:
  soketi:
    image: quay.io/soketi/soketi:latest
    container_name: soketi
    restart: unless-stopped
    ports:
      - "6001:6001" # HTTP WebSocket listener
      - "6002:6002" # Optional management port
    environment:
      SOKETI_APP_ID: "${PUSHER_APP_ID:-local}"
      SOKETI_APP_KEY: "${PUSHER_APP_KEY:-local}"
      SOKETI_APP_SECRET: "${PUSHER_APP_SECRET:-local}"
      SOKETI_APP_CLUSTER: "${PUSHER_APP_CLUSTER:-mt1}"
      SOKETI_ENABLE_REDIS: "false"
    volumes:
      - soketi-data:/var/lib/soketi

volumes:
  soketi-data:
    driver: local
